// Semestre 2/livros-react/src/LivroDados.js
import { useState } from "react";
import { ControleLivro } from "./controle/ControleLivros";
import { ControleEditora } from "./controle/ControleEditora";
import { useNavigate } from "react-router-dom";

const LivroDados = () => {
	const controleLivro = new ControleLivro();
	const controleEditora = new ControleEditora();

	const opcoes = controleEditora
		.getEditoras()
		.map((editora) => ({ value: editora.codEditora, text: editora.nome }));

	const [titulo, setTitulo] = useState("");
	const [resumo, setResumo] = useState("");
	const [autores, setAutores] = useState("");
	const [codEditora, setCodEditora] = useState(opcoes[0].value);

	const navigate = useNavigate();

	const tratarCombo = (evento) => {
		const value = parseInt(evento.target.value);
		setCodEditora(value);
	};

	const incluir = (evento) => {
		evento.preventDefault();

		const livro = {
			codigo: 0,
			codEditora: codEditora,
			titulo: titulo,
			resumo: resumo,
			autores: autores.split("\n"),
		};

		controleLivro.incluir(livro);

		navigate("/");
	};

	return (
		<main className="w-75 text-start mx-auto">
			<h1>Dados do Livro</h1>

			<form onSubmit={(e) => incluir(e)}>
				<div className="mb-3">
					<label htmlFor="titulo" className="form-label">
						Título
					</label>

					<input
						type="text"
						id="titulo"
						onChange={(e) => setTitulo(e.target.value)}
						className="form-control"
					/>
				</div>

				<div className="mb-3">
					<label htmlFor="resumo" className="form-label">
						Resumo
					</label>

					<textarea
						type="text"
						id="resumo"
						onChange={(e) => setResumo(e.target.value)}
						className="form-control"
					/>
				</div>

				<div className="mb-3">
					<label htmlFor="editora" className="form-label">
						Editora
					</label>

					<select
						name="cars"
						id="cars"
						onChange={(e) => tratarCombo(e)}
						className="form-control"
					>
						{opcoes.map((opcao) => {
							return (
								<option key={opcao.value} value={opcao.value}>
									{opcao.text}
								</option>
							);
						})}
					</select>
				</div>

				<div className="mb-3">
					<label htmlFor="autores" className="form-label">
						Autores (1 por linha)
					</label>

					<textarea
						type="text"
						id="autores"
						onChange={(e) => setAutores(e.target.value)}
						className="form-control"
					/>
				</div>

				<button type="submit" className="btn btn-primary">
					Salvar Dados
				</button>
			</form>
		</main>
	);
};

export default LivroDados;

// Semestre 2/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "app-livro-dados",
    templateUrl: "./livro-dados.component.html",
    styleUrls: ["./livro-dados.component.css"],
})
export class LivroDadosComponent {}

<main class="container">
    <h1>Dados do Livro</h1>

    <form (submit)="incluir()" ngNativeValidate>
        <div class="mb-3">
            <label htmlFor="titulo" class="form-label">Título</label>

            <input
                type="text"
                id="titulo"
                [(ngModel)]="livro.titulo"
                [ngModelOptions]="{ standalone: true }"
                class="form-control"
                required
            />
        </div>

        <div class="mb-3">
            <label htmlFor="resumo" class="form-label">Resumo</label>

            <textarea
                id="resumo"
                [(ngModel)]="livro.resumo"
                [ngModelOptions]="{ standalone: true }"
                class="form-control"
                required
            ></textarea>
        </div>

        <div class="mb-3">
            <label htmlFor="editoras" class="form-label">Editora</label>

            <select
                name="editoras"
                id="editoras"
                [(ngModel)]="livro.codEditora"
                [ngModelOptions]="{ standalone: true }"
                class="form-control"
                required
            >
                <option
                    *ngFor="let editora of editoras"
                    value="{{ editora.codEditora }}"
                >
                    {{ editora.nome }}
                </option>
            </select>
        </div>

        <div class="mb-3">
            <label htmlFor="autores" class="form-label">
                Autores (1 por linha)
            </label>

            <textarea
                id="autores"
                [(ngModel)]="autoresForm"
                [ngModelOptions]="{ standalone: true }"
                class="form-control"
                required
            ></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
</main>
