// Semestre 2/livraria/clientes/livros-next/pages/LivroDados.tsx
// classes / components
import { ControleEditora } from "@/classes/controle/ControleEditora";
import { Livro } from "@/classes/modelo/Livro";
import { Menu } from "@/componentes/Menu";

// React / Next
import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

// styles
import styles from "@/styles/Home.module.css";
import { ControleLivro } from "@/classes/controle/ControleLivros";

const controleEditora = new ControleEditora();
const controleLivros = new ControleLivro();

const LivroDados: NextPage = () => {
	const editoras = controleEditora.getEditoras();
	const opcoes = editoras.map((editora) => ({
		value: editora.codEditora,
		text: editora.nome,
	}));

	const [titulo, setTitulo] = useState("");
	const [resumo, setResumo] = useState("");
	const [autores, setAutores] = useState("");
	const [codEditora, setCodEditora] = useState(opcoes[0].value);

	const router = useRouter();

	const tratarCombo = (evento: React.ChangeEvent<HTMLSelectElement>) => {
		setCodEditora(+evento.target.value);
	};

	const incluir = (evento: React.FormEvent<HTMLFormElement>) => {
		evento.preventDefault();

		const livro = {
			codigo: null,
			codEditora: codEditora,
			titulo: titulo,
			resumo: resumo,
			autores: autores.split("\n"),
		};

		controleLivros.incluir(livro).then(() => router.push("/LivroLista"));
	};

	return (
		<>
			<Head>
				<title>Loja Next</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Menu />

			<main className={styles.main}>
				<h1 className={styles.title}></h1>

				<form onSubmit={(e) => incluir(e)}>
					<div className="mb-3">
						<label htmlFor="titulo" className="form-label">
							Título
						</label>

						<input
							type="text"
							id="titulo"
							onChange={(e) => setTitulo(e.target.value)}
							className="form-control"
							required
						/>
					</div>

					<div className="mb-3">
						<label htmlFor="resumo" className="form-label">
							Resumo
						</label>

						<textarea
							id="resumo"
							onChange={(e) => setResumo(e.target.value)}
							className="form-control"
							required
						/>
					</div>

					<div className="mb-3">
						<label htmlFor="editoras" className="form-label">
							Editora
						</label>

						<select
							name="editoras"
							id="editoras"
							onChange={(e) => tratarCombo(e)}
							className="form-control"
							required
						>
							{opcoes.map((opcao) => {
								return (
									<option
										key={opcao.value}
										value={opcao.value}
									>
										{opcao.text}
									</option>
								);
							})}
						</select>
					</div>

					<div className="mb-3">
						<label htmlFor="autores" className="form-label">
							Autores (1 por linha)
						</label>

						<textarea
							id="autores"
							onChange={(e) => setAutores(e.target.value)}
							className="form-control"
							required
						/>
					</div>

					<button type="submit" className="btn btn-primary">
						Salvar Dados
					</button>
				</form>
			</main>
		</>
	);
};

export default LivroDados;

// Semestre 2/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "app-livro-dados",
    templateUrl: "./livro-dados.component.html",
    styleUrls: ["./livro-dados.component.css"],
})
export class LivroDadosComponent {}

<main class="container">
    <h1>Dados do Livro</h1>

    <form (submit)="incluir()" ngNativeValidate>
        <div class="mb-3">
            <label htmlFor="titulo" class="form-label">Título</label>

            <input
                type="text"
                id="titulo"
                [(ngModel)]="livro.titulo"
                [ngModelOptions]="{ standalone: true }"
                class="form-control"
                required
            />
        </div>

        <div class="mb-3">
            <label htmlFor="resumo" class="form-label">Resumo</label>

            <textarea
                id="resumo"
                [(ngModel)]="livro.resumo"
                [ngModelOptions]="{ standalone: true }"
                class="form-control"
                required
            ></textarea>
        </div>

        <div class="mb-3">
            <label htmlFor="editoras" class="form-label">Editora</label>

            <select
                name="editoras"
                id="editoras"
                [(ngModel)]="livro.codEditora"
                [ngModelOptions]="{ standalone: true }"
                class="form-control"
                required
            >
                <option
                    *ngFor="let editora of editoras"
                    value="{{ editora.codEditora }}"
                >
                    {{ editora.nome }}
                </option>
            </select>
        </div>

        <div class="mb-3">
            <label htmlFor="autores" class="form-label">
                Autores (1 por linha)
            </label>

            <textarea
                id="autores"
                [(ngModel)]="autoresForm"
                [ngModelOptions]="{ standalone: true }"
                class="form-control"
                required
            ></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
</main>
