// Semestre 2/livraria/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from "@angular/core";
import { Editora } from "../editora";
import { Livro } from "../livro";
import { ControleEditoraService } from "../controle-editora.service";
import { ControleLivrosService } from "../controle-livros.service";

@Component({
    selector: "app-livro-lista",
    templateUrl: "./livro-lista.component.html",
    styleUrls: ["./livro-lista.component.css"],
})
export class LivroListaComponent implements OnInit {
    public editoras: Array<Editora> = [];
    public livros: Array<Livro> = [];

    constructor(
        private servEditora: ControleEditoraService,
        private servLivros: ControleLivrosService
    ) {}

    async ngOnInit() {
        await this.obterTodos();
    }

    obterTodos = async () => {
        await this.servLivros
            .obterLivros()
            .then((result) => (this.livros = result));
    };

    excluir = async (codigo: string) => {
        await this.servLivros
            .excluir(codigo)
            .then(async () => await this.obterTodos());
    };

    obterNome = (codEditora: number) => {
        return this.servEditora.getNomeEditora(codEditora);
    };
}

<main class="container">
    <h1>Catálogo de Livros</h1>

    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>

        <tbody>
            <tr *ngFor="let livro of livros">
                <td>
                    {{ livro.titulo }}
                    <br />
                    <button
                        type="button"
                        class="btn btn-danger"
                        (click)="excluir(livro.codigo!)"
                    >
                        Excluir
                    </button>
                </td>

                <td>{{ livro.resumo }}</td>
                <td>{{ obterNome(+livro.codEditora) }}</td>

                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>

// Semestre 2/livraria/clientes/livros-react/src/LivroLista.js
import { useEffect, useState } from "react";
import LinhaLivro from "./components/LinhaLivro";
import { ControleLivro } from "./controle/ControleLivros";

const controleLivro = new ControleLivro();

const LivroLista = () => {
	const [livros, setLivros] = useState();
	const [carregado, setCarregado] = useState(false);

	useEffect(() => {
		const obterTodos = async () => {
			await controleLivro
				.obterLivros()
				.then((resultado) => setLivros(resultado));

			setCarregado(true);
		};

		obterTodos();
	}, [carregado]);

	const excluir = (codigo) => {
		controleLivro.excluir(codigo).then(setCarregado(false));
	};

	return (
		<main className="w-75 text-start mx-auto">
			<h1>Catálogo de Livros</h1>

			<table className="table">
				<thead className="table-dark">
					<tr>
						<th>Título</th>
						<th>Resumo</th>
						<th>Editora</th>
						<th>Autores</th>
					</tr>
				</thead>

				<tbody>
					{carregado &&
						livros.map((livro, index) => (
							<LinhaLivro
								livro={livro}
								excluir={excluir}
								key={index}
							/>
						))}
				</tbody>
			</table>
		</main>
	);
};

export default LivroLista;
